### ISSUE TITLE
cuda requirement

### ISSUE THREAD

**Issue by bpops** [microsoft/Bringing-Old-Photos-Back-to-Life#6]
Is it possible to run this on a (recent) Mac, which does not support CUDA? I would have guessed setting --GPU 0 would not attempt to call CUDA, but it fails. 

```
File "/Users/../Desktop/bopbtl/venv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 61, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by loretoparisi** [comment]
@bpops in my case it fails with the following error:

```
(.venv) mbploreto:Bringing-Old-Photos-Back-to-Life loretoparisi$ python run.py --input_folder noscratch/ --output_folder cleaned/ --GPU 0
Running Stage 1: Overall restoration
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    opt = TestOptions().parse(save=False)
  File "/Users/loretoparisi/Documents/Projects/AI/Bringing-Old-Photos-Back-to-Life/Global/options/base_options.py", line 350, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    for x in os.listdir(stage_1_results):
FileNotFoundError: [Errno 2] No such file or directory: 'cleaned/stage_1_restore_output/restored_image'
```

**Comment by bpops** [comment]
@loretoparisi you are correct. Apologies. I was commenting some lines out to try and get past the initial error and landed on the one I quoted above.

**Comment by zhangmozhe** [comment]
Hi, you can try our Colab demo, which can leverage online GPU for running~

**Comment by bjwest** [comment]
Where is this Colab demo, and will this work on Linux utilizing it?

**Comment by bpops** [comment]
@zhangmozhe yes, I was able to get this working with the colab demo. I noticed you labelled this good first issue. Does that mean there is a straight-forward way to remove cuda requirement? If you can give me some direection, I'd be willing to take it on. Just no clue where to start.

**Comment by zhangmozhe** [comment]
@bpops We realized many users have the similar demand for the testing on CPU.  We plan to modify the code and adapt it on CPU. Since this is a research project, the speed is not optimized. So the running on CPU may take considerable time. Or you can export the model to onnx runtime, and deploy the model according to the device type.

**Comment by dpnchl** [comment]
Cuda on Torch is only available to High Sierra (10.13) users since Nvidia dropped Cuda support. An alternative library or CPU as fallback will be most beneficial for the future of this project.

[Source: https://www.provideocoalition.com/officially-official-nvidia-drops-cuda-support-for-macos]

**Comment by Rumlinv** [comment]
Torch doesn't support older graphics cards recently.  Old Torch 0.4.1 version work with old video cards but doesn't work with Bringing-Old-Photos-Back-to-Life.

**Comment by b3z** [comment]
So what's the solution here? Is it possible to run it on e.g Intel Iris Plus Graphics ?

**Comment by orngeatom** [comment]
i also encountered this error and am trying to run this with a 3070, cuda updated , torch and numpy updated and still get the error. 
running with CPU works but i would rather use the GPU since i have it available... direction greatly appreciated,

**Comment by stskidmore** [comment]
Such a bummer... I know next to zero about python, but muddled my way through getting it installed, all the needed libraries and such and then landed on this same issue. I get errors in the collab environment, which is why I decided to try it running locally.

**Comment by WMRamadan** [comment]
It says in the README that you can set GPU to -1 to use CPU, so in that case is this issue resolved?

**Comment by zhangmozhe** [comment]
> It says in the README that you can set GPU to -1 to use CPU, so in that case is this issue resolved?

Yes, the code can now support the CPU testing.
