### ISSUE TITLE
cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by wang7143** [microsoft/Bringing-Old-Photos-Back-to-Life#66]
Running Stage 1: Overall restoration
Now you are processing 5d6bfe49ge1b23ec32641&690.jpg
Skip 5d6bfe49ge1b23ec32641&690.jpg due to an error:
cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([1, 3, 470, 446], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(3, 64, kernel_size=[7, 7], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x54bd8730
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 1, 3, 470, 446,
    strideA = 628860, 209620, 446, 1,
output: TensorDescriptor 0x54bda2f0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 1, 64, 464, 440,
    strideA = 13066240, 204160, 440, 1,
weight: FilterDescriptor 0x3b058e0
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 64, 3, 7, 7,
Pointer addresses:
    input: 0x60b80c400
    output: 0x60be60000
    weight: 0x601660000

Skipping non-file final_output
Skipping non-file stage_1_restore_output
Skipping non-file stage_2_detection_output
Skipping non-file stage_3_face_output
Now you are processing timg.jpg
Skip timg.jpg due to an error:
CUDA error: an illegal memory access was encountered
Finish Stage 1 ...

Is this because of insufficient video memory?

**Comment by zhangmozhe** [comment]
Have you tried our Colab demo to restore your images? I have not met this issue. Usually, the system will directly prompt the out-of-memory error

**Comment by wang7143** [comment]
> Have you tried our Colab demo to restore your images? I have not met this issue. Usually, the system will directly prompt the out-of-memory error
My system is windows subsystem ubuntu 20.04. Could it be that this system is incomplete and does not support the use of graphics cards?I installed the dedicated graphics driver for the subsystem according to the official method，I use the python interactive mode in the sub-system. Torch can call the graphics card. I only know these at present.

**Comment by zhangmozhe** [comment]
Do you use WSL2 which supports GPU compute?

**Comment by wang7143** [comment]
> Do you use WSL2 which supports GPU compute?

yes

**Comment by zhangmozhe** [comment]
Have you tried to run the snippet code like this:

```
import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([1, 3, 470, 446], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(3, 64, kernel_size=[7, 7], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()
```

Please ensure that you can successfully run this code before you test the project.

**Comment by wang7143** [comment]
> Have you tried to run the snippet code like this:
> 
> ```
> import torch
> torch.backends.cuda.matmul.allow_tf32 = True
> torch.backends.cudnn.benchmark = True
> torch.backends.cudnn.deterministic = False
> torch.backends.cudnn.allow_tf32 = True
> data = torch.randn([1, 3, 470, 446], dtype=torch.float, device='cuda', requires_grad=True)
> net = torch.nn.Conv2d(3, 64, kernel_size=[7, 7], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
> net = net.cuda().float()
> out = net(data)
> out.backward(torch.randn_like(out))
> torch.cuda.synchronize()
> ```
> 
> Please ensure that you can successfully run this code before you test the project. If it does not work, it is more likely to be a Pytorch installation error.

Traceback (most recent call last):
  File "/home/ubuntu/Bringing-Old-Photos-Back-to-Life/test.py", line 9, in <module>
    out = net(data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

**Comment by zhangmozhe** [comment]
It's related to your cuda or cudnn installation. Please refer to https://github.com/pytorch/pytorch/issues/22050#issue-458933126 or  https://github.com/pytorch/pytorch/issues/45769#issue-713885184. Please ensure you can run the snippet code before you run this project.

**Comment by wang7143** [comment]
> It's related to your cuda or cudnn installation. Please refer to [pytorch/pytorch#22050 (comment)](https://github.com/pytorch/pytorch/issues/22050#issue-458933126) or [pytorch/pytorch#45769 (comment)](https://github.com/pytorch/pytorch/issues/45769#issue-713885184). Please ensure you can run the snippet code before you run this project.
Thank you very much for your help, my problem is solved, it doesn’t report errors anymore

**Comment by gejintaohua** [comment]
我也遇到了一模一样的问题，在运行过程中似乎的确是显存炸了，并且这台服务器这个环境可以运行其他的程序，所以很迷惑

**Comment by White1973** [comment]
可以看看是否加入nn.emdedding层，查看输入的class id是否在在构建网络时设置的class 范围内，如设置nn.embedding(10,128)，计算时，label id不能大于或等于10。

**Comment by EddieAy** [comment]
总结：大概率是你显存炸了
